%YAML 1.2
---
#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------

# Camera calibration and distortion parameters (OpenCV) 
Camera:
  fx: 600.0 
  fy: 600.0 
  cx: 599.5 
  cy: 339.5
  k1: 0.00023840576144970707
  k2: -0.00031479749960004814
  k3: 0
  p1: -7.392305313239943e-05
  p2: -2.771600122416197e-05
  width: 1200
  height: 680
# Camera frames per second
  fps: 30.0 
# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
  RGB: 1 

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

ORBextractor:
# ORB Extractor: Number of features per image
  nFeatures: 2000      
# ORB Extractor: Scale factor between levels in the scale pyramid      
  scaleFactor: 1.3 
# ORB Extractor: Number of levels in the scale pyramid
  nLevels: 8  
# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast     
  iniThFAST: 7
  minThFAST: 1

#--------------------------------------------------------------------------------------------
# NeRF Parameters
#--------------------------------------------------------------------------------------------
NeRF:
  aabb_scale: 2
  scale: 0.17
  offset: [0.5, 0.5, 0.5]
  network_config_path: "./Thirdparty/instant-ngp-kf/configs/nerf/base.json"